### ISSUE TITLE
Customer Service Menu Content

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#44] opened 2015-02-05 17:05 UTC
As discussed earlier, clicking on customer service should expand showing 4 sub-navs:
Contact Us (List to be amended)
About Us (as is for now)
Popular Customer Forms (with you, 3 forms to follow)
Careers (as is for now)
 
The reception number (01) 6172000 should show in opposite the sub-navs instead of the placeholder image to keep it consistent with the rest of the customer site navigation.

**Comment by seonzoo** [comment] 2015-02-06 15:27
Don't recall this was discussed. Will need a half-height phone number graphic if there are only 2x2 subnav items

**Comment by seonzoo** [comment] 2015-02-06 17:29
DUPLICATE OF #32

**Closed** 2015-02-06 17:29 UTC
Labels: invalid
