### ISSUE TITLE
Investing & what does it mean - add images

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#91] opened 2015-02-16 12:25 UTC
Add images to page layout (from GF email 16/02/15)

**Comment by seonzoo** [comment] 2015-02-16 13:41
I don't have a copy of this email - is this issue a duplicate of #53 ?

**Comment by stephnyc** [comment] 2015-02-16 14:29
images on \\server\clients\clientname\2118 NIA Website\Design\Assets (see jpgs added 16/2/15)

MB says PH should look at this first

**Closed** 2015-02-17 15:39 UTC
Labels: Design
